### ISSUE TITLE
source-git update-dist-git workflow: bot accepts dist-git commit message

### ISSUE THREAD

**Issue by TomasTomecek** [packit/hardly#96]
Just talking to @simo5 on a chat.

Simo requests to be able to configure dist-git commit message as part of the `update-dist-git` workflow when our bot creates a dist-git MR. We can already do this with CLI, but not with hardly (the bot).

quoting Simo here:
```
in source git I want explanation of what the commit does
in dist-git I want the reason why I am making a package change for a specific Y stream release (or Z stream)
```

Not sure if we can be smart about this on our side or there would be an explicit "field" to enter the commit message

Leaving this issue in Packit so we can design it first.

**Comment by lbarcziova** [comment]
Related to packit/packit#1887

**Comment by lachmanfrantisek** [comment]
Hello all the source-git lovers,

as part of a backlog cleanup, we are closing source-git-related issues because it is not our priority anymore and we don't want to provide false promises to anyone. And if we were to change the priorities, the whole source-git project would need to be revisited nevertheless.

A more detailed description of why we have come up to this decision can be found at https://packit.dev/source-git/status (most of this is still relevant), TLDR is that we can provide more benefits in other areas.

What now:
* The service part is currently being decommissioned for no real use. (It even was offline for a couple of weeks because of a certificate issue and no one realised.)
* The CLI is still there, but the Packit team won't work on these tasks. We are happy to help and accept any external contribution.
* If you find something really, really important and can't do it yourself, let us know. We might still find a way but we would need to be really sure that our time spent on this is worth the benefit.

Our current priorities are visible [on our board](https://github.com/orgs/packit/projects/7/views/29) (revisited quarterly) and are based on user benefit and demand. (=> You can influence that..;)

Thank you for your valuable feedback and for believing in source-git -- hopefully, someone will continue this way (happy to provide all the findings and code!). But we don't want to lie to you about the current state of source-git in the team.

František
